<?php

/**
 * @file
 * A custom module for Drupal 7, named 'easyddb_ee_pdf'.
 */

/**
 * Implements hook_help().
 */
function easyddb_ee_pdf_help($path, $arg) {
  if ($path == 'admin/help#easyddb_ee_pdf') {
    return t('Module for generating events list as PDF file.');
  }
}

/**
 * Implements hook_menu().
 */
function easyddb_ee_pdf_menu() {
  $items = [];

  $items['admin/content/pdf'] = [
    'title' => 'Events PDF',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['easyddb_ee_pdf_generate_pdf_form'],
    'access arguments' => array('generate events pdf'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'easyddb_ee_pdf.pdf.inc',
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function easyddb_ee_pdf_permission() {
  return [
    'generate events pdf' => [
      'title' => t('Generate events list as PDF'),
      'description' => t('Check this to allow access to the page to generate events list as a PDF file.'),
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function easyddb_ee_pdf_theme($existing, $type, $theme, $path) {
  return array(
    'ee_pdf_event' => array(
      'variables' => array('event' => NULL),
      'template' => 'templates/ee_pdf_event',
    ),
    'ee_pdf_header' => array(
      'variables' => array('title' => NULL),
      'template' => 'templates/ee_pdf_header',
    ),
    'ee_pdf_footer' => array(
      'variables' => array('title' => NULL),
      'template' => 'templates/ee_pdf_footer',
    ),
  );
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_ee_pdf_event(array &$variables) {
  $event = $variables['event'];

  $library_reference = field_get_items('node', $event, 'og_group_ref');
  $library_node = node_load($library_reference[0]['target_id'] ?? NULL);
  $variables['event_library'] = $library_node ? $library_node->title : '';

  $event_date = field_get_items('node', $event, 'field_ding_event_date');
  $event_date = $event_date[0] ?? '';
  if ($event_date['value']) {
    $event_date_obj = (DateTime::createFromFormat(
      'Y-m-d H:i:s',
      $event_date['value'],
      (new \DateTimeZone($event_date['timezone_db']))
    ));
    $event_date_obj->setTimezone((new \DateTimeZone($event_date['timezone'])));
  }
  $variables['event_date'] = $event_date_obj->format('Y-m-d H:i:s');

  $event_location = field_get_items('node', $event, 'field_ding_event_location');
  $variables['event_location'] = implode(', ',
    array_filter([
      $event_location[0]['thoroughfare'] ?? '',
      $event_location[0]['locality'] ?? '',
    ])
  );

  $event_description = field_get_items('node', $event, 'field_ding_event_body');
  $variables['event_description'] = $event_description[0]['safe_value'] ?? '';
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_ee_pdf_header(array &$variables) {
  $category_term = $variables['category_term'];

  $variables['title'] = $category_term->name ?? '';
}
